spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/springboot?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
#    password:
server:
  context-path: /sell

wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: xxxxxxxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: D:/var/weixin_cert/h5.p12
  notifyUrl: http://zzxishero.natapp1.cc/sell/pay/notify
#  templated:
#    orderStatus:

#projectUrl:
#  wechatMpAuthorize: http://zzxishero.natapp1.cc
#  wechatOpenAuthorize: http://zzxishero.natapp1.cc
#  sell: http://zzxishero.natapp1.cc

#logging:
#  level:
#    com.zzx.dataobject.mapper: trace
#  pattern:
#    console: "%d - %msg%n"
#  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell/

mybatis:
  mapper-locations: classpath:mapper/*.xml
